name: Build/test
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      # - run: npm run build
      - run: npm test
